INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('DEPARTAMENTO DE PROPAGANDA Y AGITACIÓN (DPA)','Entity','DPRK','09/11/2017','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('7TH OF TIR','Entity','Iran','12/23/2006',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ABDALLAH AZZAM BRIGADES (AAB)','Entity','Al-Qaida','09/23/2014',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ABU SAYYAF GROUP','Entity','Al-Qaida','10/06/2001','Philippines');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ABZAR BORESH KAVEH CO. (BK CO.)','Entity','Iran','03/03/2008',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ACADEMY OF NATIONAL DEFENSE SCIENCE','Entity','DPRK','03/02/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ADF','Entity','DRC','06/30/2014','Democratic Republic of the Congo');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AFGHAN SUPPORT COMMITTEE (ASC)','Entity','Al-Qaida','01/11/2002','Pakistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL FURQAN','Entity','Al-Qaida','05/11/2004','Bosnia and Herzegovina');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL MOUAKAOUNE BIDDAM','Entity','Al-Qaida','06/02/2014','Mali');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL MOULATHAMOUN','Entity','Al-Qaida','06/02/2014','Mali');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL MOURABITOUN','Entity','Al-Qaida','06/02/2014','Mali');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL RASHID TRUST','Entity','Al-Qaida','10/06/2001','Pakistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL WASEL AND BABEL GENERAL TRADING LLC','Entity','Iraq','04/26/2004','United Arab Emirates');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-AKHTAR TRUST INTERNATIONAL','Entity','Al-Qaida','08/17/2005','Pakistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-BASHAIR TRADING COMPANY LTD','Entity','Iraq','04/26/2004','Iraq');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-HARAMAIN & AL MASJED AL-AQSA CHARITY FOUNDATION','Entity','Al-Qaida','06/28/2004','Bosnia and Herzegovina');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-HARAMAIN FOUNDATION (PAKISTAN)','Entity','Al-Qaida','01/26/2004','Pakistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-HARAMAIN FOUNDATION (UNION OF THE COMOROS)','Entity','Al-Qaida','09/28/2004','Union of the Comoros');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-HARAMAIN: AFGHANISTAN BRANCH','Entity','Al-Qaida','07/06/2004','Afghanistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-HARAMAIN: ALBANIA BRANCH','Entity','Al-Qaida','07/06/2004','Albania');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-HARAMAIN: BANGLADESH BRANCH','Entity','Al-Qaida','07/06/2004','Bangladesh');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-HARAMAIN: ETHIOPIA BRANCH','Entity','Al-Qaida','07/06/2004','Ethiopia');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-HARAMAIN: THE NETHERLANDS BRANCH','Entity','Al-Qaida','07/06/2004','The Netherlands');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-HARAMAYN FOUNDATION (KENYA)','Entity','Al-Qaida','01/26/2004','Kenya');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-HARAMAYN FOUNDATION (TANZANIA)','Entity','Al-Qaida','01/26/2004','Tanzania');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-ITIHAAD AL-ISLAMIYA / AIAI','Entity','Al-Qaida','10/06/2001',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-KAWTHAR MONEY EXCHANGE','Entity','Al-Qaida','03/06/2018','Iraq');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-NUSRAH FRONT FOR THE PEOPLE OF THE LEVANT','Entity','Al-Qaida','05/14/2014','Syrian Arab Republic');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-QAIDA','Entity','Al-Qaida','10/06/2001',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-QAIDA IN IRAQ','Entity','Al-Qaida','10/18/2004',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-QAIDA IN THE ARABIAN PENINSULA (AQAP)','Entity','Al-Qaida','01/19/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AL-SHABAAB','Entity','Somalia','04/12/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ALFA COMPANY LIMITED FOR INTERNATIONAL TRADING AND MARKETING','Entity','Iraq','06/02/2004','Jordan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AMIN INDUSTRIAL COMPLEX','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AMMUNITION AND METALLURGY INDUSTRIES GROUP (AMIG)','Entity','Iran','03/24/2007',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AMROGGANG DEVELOPMENT BANKING CORPORATION','Entity','DPRK','05/02/2012','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ANSAR AL CHARIA BENGHAZI','Entity','Al-Qaida','11/19/2014',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ANSAR AL CHARIA DERNA','Entity','Al-Qaida','11/19/2014',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ANSAR AL-ISLAM','Entity','Al-Qaida','02/24/2003',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ANSAR AL-SHARIâ€™A IN Tunisia (AAS-T)','Entity','Al-Qaida','09/23/2014','Tunisia');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ANSAR EDDINE','Entity','Al-Qaida','03/20/2013','Mali');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ANSARUL MUSLIMINA FI BILADIS SUDAN','Entity','Al-Qaida','06/26/2014','Nigeria');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ARMAMENT INDUSTRIES GROUP (AIG)','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ARMED ISLAMIC GROUP','Entity','Al-Qaida','10/06/2001','Algeria');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ASBAT AL-ANSAR','Entity','Al-Qaida','10/06/2001','Lebanon');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('AVIATRANS ANSTALT','Entity','Iraq','04/26/2004','Liechtenstein');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('Al-ARABI TRADING COMPANY','Entity','Iraq','04/26/2004','Iraq');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('BANK OF EAST LAND','Entity','DPRK','01/22/2013','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('BARZAGANI TEJARAT TAVANMAD SACCAL COMPANIES','Entity','Iran','03/03/2008',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('BEHINEH TRADING CO.','Entity','Iran','04/18/2012','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('BENEVOLENCE INTERNATIONAL FOUNDATION','Entity','Al-Qaida','11/21/2002','United States of America');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('BUTEMBO AIRLINES (BAL)','Entity','DRC','03/29/2007','Democratic Republic of the Congo');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('COMISIÃ“N MILITAR CENTRAL DEL PARTIDO DE LOS TRABAJADORES DE COREA (CMC)','Entity','DPRK','09/11/2017','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('CHANG AN SHIPPING & TECHNOLOGY','Entity','DPRK','03/30/2018','China');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('CHONGCHONGANG SHIPPING COMPANY','Entity','DPRK','03/02/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('CHONMYONG SHIPPING CO','Entity','DPRK','03/30/2018','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('COMPAGNIE AERIENNE DES GRANDS LACS (CAGL) ; GREAT LAKES BUSINESS COMPANY (GLBC)','Entity','DRC','03/29/2007','Democratic Republic of the Congo');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('CONGOMET TRADING HOUSE','Entity','DRC','03/29/2007',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('CRUISE MISSILE INDUSTRY GROUP','Entity','Iran','03/24/2007',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('DAEDONG CREDIT BANK (DCB)','Entity','DPRK','03/02/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('DCB FINANCE LIMITED','Entity','DPRK','11/30/2016','British Virgin Islands');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('DEFENCE INDUSTRIES ORGANISATION (DIO)','Entity','Iran','12/23/2006',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('DEFENSE TECHNOLOGY AND SCIENCE RESEARCH CENTER (DTSRC)','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('DOOSTAN INTERNATIONAL COMPANY (DICO)','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('EASTERN TURKISTAN ISLAMIC MOVEMENT (ETIM)','Entity','Al-Qaida','09/11/2002',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('EGYPTIAN ISLAMIC JIHAD','Entity','Al-Qaida','10/06/2001',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ELECTRO SANAM COMPANY','Entity','Iran','03/03/2008',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('EMARAT KAVKAZ','Entity','Al-Qaida','07/29/2011',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ETTEHAD TECHNICAL GROUP','Entity','Iran','03/03/2008',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('FAJR INDUSTRIAL GROUP','Entity','Iran','12/23/2006',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('FARASAKHT INDUSTRIES','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('FARAYAND TECHNIQUE','Entity','Iran','12/23/2006',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('FATER INSTITUTE','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('FIRST OIL JV CO LTD','Entity','DPRK','03/30/2018','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('FORCES DEMOCRATIQUES DE LIBERATION DU RWANDA (FDLR)','Entity','DRC','12/31/2012','Democratic Republic of the Congo');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('FOREIGN TRADE BANK (FTB)','Entity','DPRK','08/05/2017','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('GENERAL BUREAU OF ATOMIC ENERGY (GBAE)','Entity','DPRK','07/16/2009','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('GHARAGAHE SAZANDEGI GHAEM','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('GHORB KARBALA','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('GHORB NOOH','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('GLOBAL RELIEF FOUNDATION (GRF)','Entity','Al-Qaida','10/22/2002','United States of America');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('GREEN PINE ASSOCIATED CORPORATION','Entity','DPRK','05/02/2012','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('HAJI BASIR AND ZARJMIL COMPANY HAWALA','Entity','Taliban','2015-03-27-04:00','Pakistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE','Entity','Taliban','06/29/2012','Pakistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('HANIFA MONEY EXCHANGE OFFICE (BRANCH LOCATED IN ALBU KAMAL SYRIAN ARAB REPUBLIC)','Entity','Al-Qaida','07/20/2017','Syrian Arab Republic');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('HAPJANGGANG SHIPPING CORP','Entity','DPRK','03/30/2018','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('HAQQANI NETWORK (HQN)','Entity','Taliban','11/05/2012',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('HARA COMPANY','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('HARAKAT SHAM AL-ISLAM','Entity','Al-Qaida','02/29/2016',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('HARAKAT UL-MUJAHIDIN / HUM','Entity','Al-Qaida','10/06/2001','Pakistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('HARAKAT-UL JIHAD ISLAMI','Entity','Al-Qaida','08/06/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('HESONG TRADING COMPANY','Entity','DPRK','03/02/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('HILAL AHMAR SOCIETY INDONESIA (HASI)','Entity','Al-Qaida','03/13/2015',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('HONG KONG ELECTRONICS','Entity','DPRK','07/16/2009','RepÃºblica IslÃ¡mica del IrÃ¡n');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('HUAXIN SHIPPING HONGKONG LTD','Entity','DPRK','03/30/2018','China');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('IDLEB COMPANY FOR SPINNING','Entity','Iraq','04/26/2004','Iraq');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ILSIM INTERNATIONAL BANK','Entity','DPRK','11/30/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('IMENSAZAN CONSULTANT ENGINEERS INSTITUTE','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('INDUSTRIAL FACTORIES OF PRECISION (IFP) MACHINERY','Entity','Iran','03/03/2008',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ISLAMIC ARMY OF ADEN','Entity','Al-Qaida','10/06/2001',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ISLAMIC INTERNATIONAL BRIGADE (IIB)','Entity','Al-Qaida','03/04/2003',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ISLAMIC JIHAD GROUP','Entity','Al-Qaida','06/01/2005',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ISLAMIC MOVEMENT OF UZBEKISTAN','Entity','Al-Qaida','10/06/2001',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ISLAMIC STATE IN IRAQ AND THE LEVANT - KHORASAN (ISIL-K)','Entity','Al-Qaida','05/14/2019',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ISLAMIC STATE IN IRAQ AND THE LEVANT - LIBYA','Entity','Al-Qaida','03/04/2020',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ISLAMIC STATE IN IRAQ AND THE LEVANT - YEMEN','Entity','Al-Qaida','03/04/2020',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ISLAMIC STATE IN THE GREATER SAHARA (ISGS)','Entity','Al-Qaida','02/23/2020',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ISLAMIC STATE WEST AFRICA PROVINCE (ISWAP)','Entity','Al-Qaida','02/23/2020',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('Islamic State In Iraq And the Levant In South-East Asia','Entity','Al-Qaida',NULL,NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('JAISH-I-MOHAMMED','Entity','Al-Qaida','10/17/2001','Pakistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('JAMYAH TAAWUN AL-ISLAMIA','Entity','Al-Qaida','10/17/2001','Afghanistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('JAMAA NUSRAT UL-ISLAM WA AL-MUSLIMIN (JNIM)','Entity','Al-Qaida','10/04/2018',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('JAMAATU AHLIS SUNNA LIDDAAWATI WAL-JIHAD','Entity','Al-Qaida','05/22/2014','Nigeria');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('JAMAAH ANSHARUT DAULAH','Entity','Al-Qaida','03/04/2020',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('JAMAAT-UL-AHRAR (JuA)','Entity','Al-Qaida','07/06/2017',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('JEMAAH ISLAMIYAH','Entity','Al-Qaida','10/25/2002',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('JEMMAH ANSHORUT TAUHID (JAT)','Entity','Al-Qaida','03/12/2012','Indonesia');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('JOZA INDUSTRIAL CO.','Entity','Iran','03/03/2008',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('JUND AL AQSA','Entity','Al-Qaida','07/20/2017','Syrian Arab Republic');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('JUND AL-KHILAFAH IN ALGERIA (JAK-A)','Entity','Al-Qaida','09/29/2015',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('JUND AL-KHILAFAH IN TUNISIA (JAK-T)','Entity','Al-Qaida','12/29/2021',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('Jaysh Khalid Ibn al Waleed','Entity','Al-Qaida','07/20/2017',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KALA-ELECTRIC','Entity','Iran','12/23/2006',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KANGBONG TRADING CORPORATION','Entity','DPRK','06/02/2017','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KAVEH CUTTING TOOLS COMPANY','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KHATAM AL-ANBIYA CONSTRUCTION HEADQUARTERS (KAA)','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KHATIBA AL-TAWHID WAL-JIHAD (KTJ)','Entity','Al-Qaida','03/07/2022',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KHATIBA IMAM AL-BUKHARI (KIB)','Entity','Al-Qaida','03/29/2018',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KHORASAN METALLURGY INDUSTRIES','Entity','Iran','03/03/2008',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KINGLY WON INTERNATIONAL CO. LTD','Entity','DPRK','03/30/2018','Marshall Islands');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA ACHIM SHIPPING CO','Entity','DPRK','03/30/2018','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA ANSAN SHIPPING COMPANY','Entity','DPRK','03/30/2018','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA COMPLEX EQUIPMENT IMPORT CORPORATION','Entity','DPRK','03/07/2013','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA DAESONG BANK','Entity','DPRK','11/30/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA DAESONG GENERAL TRADING CORPORATION','Entity','DPRK','11/30/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA FOREIGN TECHNICAL TRADE CENTER','Entity','DPRK','11/30/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA HEUNGJIN TRADING COMPANY','Entity','DPRK','05/02/2012','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA HYOKSIN TRADING CORPORATION','Entity','DPRK','07/16/2009','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA INTERNATIONAL CHEMICAL JOINT VENTURE COMPANY','Entity','DPRK','11/30/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA KUMRYONG TRADING CORPORATION','Entity','DPRK','01/22/2013',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA KUMSAN TRADING CORPORATION','Entity','DPRK','06/02/2017','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA KWANGSON BANKING CORPORATION (KKBC)','Entity','DPRK','03/02/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA KWANGSONG TRADING CORPORATION','Entity','DPRK','03/02/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA MINING DEVELOPMENT TRADING CORPORATION','Entity','DPRK','04/24/2009','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA MYONGDOK SHIPPING CO','Entity','DPRK','03/30/2018','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA PUGANG TRADING CORPORATION','Entity','DPRK','11/30/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA RYONBONG GENERAL CORPORATION','Entity','DPRK','04/24/2009','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA RYONHA MACHINERY JOINT VENTURE CORPORATION','Entity','DPRK','01/22/2013','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA SAMJONG SHIPPING','Entity','DPRK','03/30/2018','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA SAMMA SHIPPING CO','Entity','DPRK','03/30/2018','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA TAESONG TRADING COMPANY','Entity','DPRK','11/30/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA UNITED DEVELOPMENT BANK','Entity','DPRK','11/30/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREA YUJONG SHIPPING CO LTD','Entity','DPRK','03/30/2018','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREAN COMMITTEE FOR SPACE TECHNOLOGY','Entity','DPRK','01/22/2013','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREAN NATIONAL INSURANCE COMPANY (KNIC)','Entity','DPRK','08/05/2017','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOREAN TANGUN TRADING CORPORATION','Entity','DPRK','07/16/2009','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KORYO BANK','Entity','DPRK','06/02/2017','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KORYO CREDIT DEVELOPMENT BANK','Entity','DPRK','08/05/2017','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('KOTI CORP','Entity','DPRK','03/30/2018','Panama');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('LASHKAR I JHANGVI (LJ)','Entity','Al-Qaida','02/03/2003',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('LASHKAR-E-TAYYIBA','Entity','Al-Qaida','05/02/2005',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('LEADER (HONG KONG) INTERNATIONAL','Entity','DPRK','01/22/2013','Hong Kong Special Administrative Region');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('LIBYAN AFRICA INVESTMENT PORTFOLIO','Entity','Libya','03/17/2011','Libya');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('LIBYAN INVESTMENT AUTHORITY','Entity','Libya','03/17/2011','Libya');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('LIBYAN ISLAMIC FIGHTING GROUP','Entity','Al-Qaida','10/06/2001','Libya');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('LOGARCHEO S.A.','Entity','Iraq','04/26/2004','Switzerland');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('LORDâ€™S RESISTANCE ARMY','Entity','CAR','03/07/2016','Central African Republic');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('M. BABAIE INDUSTRIES','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('M23','Entity','DRC','12/31/2012',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MACHANGA LTD','Entity','DRC','03/29/2007','Uganda');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MAKHTAB AL-KHIDAMAT','Entity','Al-Qaida','10/06/2001',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MAKIN','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MALEK ASHTAR UNIVERSITY','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MANSUDAE OVERSEAS PROJECT GROUP OF COMPANIES','Entity','DPRK','08/05/2017','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MINISTRY OF ATOMIC ENERGY INDUSTRY','Entity','DPRK','03/02/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MINISTRY OF DEFENSE LOGISTICS EXPORT','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MINISTERIO DE LAS FUERZAS ARMADAS DEL PUEBLO (MFAP)','Entity','DPRK','12/22/2017','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MIZAN MACHINERY MANUFACTURING','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MOROCCAN ISLAMIC COMBATANT GROUP','Entity','Al-Qaida','10/10/2002','Morocco');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MOUVEMENT POUR','Entity','Al-Qaida','12/05/2012','Mali');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MUHAMMAD JAMAL NETWORK (MJN)','Entity','Al-Qaida','10/21/2013',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MUJAHIDIN INDONESIAN TIMUR (MIT)','Entity','Al-Qaida','09/29/2015',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MUNITIONS INDUSTRY DEPARTMENT','Entity','DPRK','03/02/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('MYOHYANG SHIPPING CO','Entity','DPRK','03/30/2018','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('NAMCHONGANG TRADING CORPORATION','Entity','DPRK','07/16/2009','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('NATIONAL AEROSPACE DEVELOPMENT ADMINISTRATION','Entity','DPRK','03/02/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('NIRU BATTERY MANUFACTURING COMPANY','Entity','Iran','03/03/2008',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('OCEAN MARITIME MANAGEMENT COMPANY LIMITED (OMM)','Entity','DPRK','07/28/2014','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('OFFICE 39','Entity','DPRK','03/02/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('OMRAN SAHEL','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('DEPARTAMENTO DE ORGANIZACIÃ“N Y ORIENTACIÃ“N (DOO)','Entity','DPRK','09/11/2017','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ORIENTAL OIL KISH','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('PAEKMA SHIPPING CO','Entity','DPRK','03/30/2018','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('PARCHIN CHEMICAL INDUSTRIES','Entity','Iran','03/24/2007',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('PARS AVIATION SERVICES COMPANY','Entity','Iran','03/24/2007',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('PEJMAN INDUSTRIAL SERVICES CORPORATION','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('PHYONGCHON SHIPPING & MARINE','Entity','DPRK','03/30/2018','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('PRO-GAIN GROUP CORPORATION','Entity','DPRK','03/30/2018',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('QODS AERONAUTICS INDUSTRIES','Entity','Iran','03/24/2007',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('RABITA TRUST','Entity','Al-Qaida','10/17/2001',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('RAH SAHEL','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('RAHAB ENGINEERING INSTITUTE','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('RAHAT LTD.','Entity','Taliban','11/21/2012','Afghanistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('RAJAH SOLAIMAN MOVEMENT','Entity','Al-Qaida','06/04/2008','Philippines');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('RECONNAISSANCE GENERAL BUREAU','Entity','DPRK','03/02/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('REVIVAL OF ISLAMIC HERITAGE SOCIETY','Entity','Al-Qaida','01/11/2002','Pakistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('RIYADUS-SALIKHIN RECONNAISSANCE AND SABOTAGE BATTALION OF CHECHEN MARTYRS (RSRSBCM)','Entity','Al-Qaida','03/04/2003',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('ROSHAN MONEY EXCHANGE','Entity','Taliban','06/29/2012','Pakistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SABALAN COMPANY','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SAD IMPORT EXPORT COMPANY','Entity','Iran','12/20/2012','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SAFETY EQUIPMENT PROCUREMENT (SEP)','Entity','Iran','03/03/2008',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SAHAND ALUMINUM PARTS INDUSTRIAL COMPANY (SAPICO)','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SAHEL CONSULTANT ENGINEERS','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SANAM INDUSTRIAL GROUP','Entity','Iran','03/24/2007',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SECOND ACADEMY OF NATURAL SCIENCES','Entity','DPRK','03/07/2013','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SECOND ECONOMIC COMMITTEE','Entity','DPRK','03/02/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SELSELAT AL-THAHAB','Entity','Al-Qaida','07/20/2017','Iraq');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SEPANIR','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SEPASAD ENGINEERING COMPANY','Entity','Iran','06/09/2010',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SHAHID BAGHERI INDUSTRIAL GROUP (SBIG)','Entity','Iran','12/23/2006',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SHAHID HEMMAT INDUSTRIAL GROUP (SHIG)','Entity','Iran','12/23/2006',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SHAHID KARRAZI INDUSTRIES','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SHAHID SATTARI INDUSTRIES','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SHAHID SAYYADE SHIRAZI INDUSTRIES (SSSI)','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SHANGHAI DONGFENG SHIPPING CO LTD','Entity','DPRK','03/30/2018','China');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SHEN ZHONG INTERNATIONAL SHIPPING','Entity','DPRK','03/30/2018','China');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SHOA AVIATION','Entity','Iran','03/24/2007',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SINGWANG ECONOMICS AND TRADING GENERAL CORPORATION','Entity','DPRK','11/30/2016','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SPECIAL INDUSTRIES GROUP (SIG)','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('SPECIAL PURPOSE ISLAMIC REGIMENT (SPIR)','Entity','Al-Qaida','03/04/2003',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('STRATEGIC ROCKET FORCE OF THE KOREAN PEOPLEâ€™S ARMY','Entity','DPRK','06/02/2017','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('T.M.G. ENGINEERING LIMITED','Entity','Iraq','05/12/2006','United Kingdom');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('TAIBAH INTERNATIONAL-BOSNIA OFFICES','Entity','Al-Qaida','05/11/2004','Bosnia and Herzegovina');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('TANCHON COMMERCIAL BANK','Entity','DPRK','04/24/2009','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('TARIQ GIDAR GROUP (TGG)','Entity','Al-Qaida','03/22/2019',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('TECHNOLOGY AND DEVELOPMENT GROUP LIMITED','Entity','Iraq','05/12/2006','United Kingdom');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('TEHRIK-E TALIBAN Pakistan (TTP)','Entity','Al-Qaida','07/29/2011',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('THE ARMY OF EMIGRANTS AND SUPPORTERS','Entity','Al-Qaida','08/06/2015','Syrian Arab Republic');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('LOS HUZÃRIES','Entity','Yemen','02/28/2022','Yemen');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('THE ORGANIZATION OF AL-QAIDA IN THE ISLAMIC MAGHREB','Entity','Al-Qaida','10/06/2001','Algeria');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('TIZ PARS','Entity','Iran','06/09/2010','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('TOSONG TECHNOLOGY TRADING CORPORATION','Entity','DPRK','01/22/2013','Democratic Peoples Republic of Korea');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('TOUS POUR LA PAIX ET LE DEVELOPPEMENT (NGO)','Entity','DRC','11/01/2005','Democratic Republic of the Congo');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('TRADING AND TRANSPORT SERVICES COMPANY LTD','Entity','Iraq','06/02/2004','Jordan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('TUNISIAN COMBATANT GROUP','Entity','Al-Qaida','10/10/2002','Tunisia');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('UGANDA COMMERCIAL IMPEX (UCI) LTD','Entity','DRC','03/29/2007','Uganda');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('UMMAH TAMEER E-NAU (UTN)','Entity','Al-Qaida','12/24/2001','Afghanistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('WAFA HUMANITARIAN ORGANIZATION','Entity','Al-Qaida','10/06/2001','Pakistan');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('WEIHAI WORLD-SHIPPING FREIGHT','Entity','DPRK','03/30/2018','China');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('YA MAHDI INDUSTRIES GROUP','Entity','Iran','03/24/2007',NULL);
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('YAS AIR','Entity','Iran','12/20/2012','Iran (Islamic Republic of)');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('YAZD METALLURGY INDUSTRIES (YMI)','Entity','Iran','06/09/2010','Iran');
INSERT INTO ONU_LIST_EN (fullName_E,sdnType_E,program_E,listed_on_E,country_E) VALUES ('YUK TUNG ENERGY PTE LTD','Entity','DPRK','03/30/2018','Singapore');
