INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Guatemala',3,1,5,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Escuintla',3,1,5,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Alta Verapaz ',1,1,5,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Chimaltenango',2,1,5,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Retalhuleu',1,1,5,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Chiquimula',1,1,5,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Huehuetenango',1,1,5,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Izabal',2,1,5,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Jutiapa',2,1,5,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Petén',1,1,5,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Quetzaltenango',3,1,5,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Sacatepéquez',1,1,5,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Sololá',1,1,5,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Ahuachapán',2,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Cabañas',1,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Chalatenango',1,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Cuscatlán',2,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('La libertad',3,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('La paz',2,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('La unión',1,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Francisco Morazán',1,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('San miguel',3,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('San salvador',3,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('San Vicente',1,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Santa Ana',3,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Sonsonate',2,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Usulután',2,1,3,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Atlántida',2,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Choluteca',2,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Colon',2,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Comayagua',2,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Copan',2,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Cortes',3,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('El Paraíso',2,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Francisco Morazán',3,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Gracias A Dios',1,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Intibucá',2,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Islas de La Bahía',1,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('La Paz',1,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Lempira',2,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Ocotepeque',1,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Olancho',2,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Santa Barbara',2,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Valle',1,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Yoro',3,1,4,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Alajuela',3,1,6,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Cartago',1,1,6,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Guanacaste',2,1,6,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Heredia',2,1,6,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Limón',2,1,6,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Puntarenas',2,1,6,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('San José',3,1,6,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Bocas del Toro',1,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Coclé',2,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Colón',3,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Chiriquí',1,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Darién',1,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Herrera',1,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Los Santos',1,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Panamá',3,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Veraguas',1,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Panamá Oeste',3,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Comarca Emberá',3,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Comarca Kuna Yala',3,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('Comarca Ngöbe Bugle',3,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('OTRO',1,1,2,1,current_timestamp());
INSERT INTO Departamento (nombreDepartamento,calificacion,idEstado,idPais,usuario_creacion,fecha_creacion) VALUES ('N/A',0,1,2,1,current_timestamp());


