INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (101,'DIRECTORES Y GERENTES PÚBLICOS Y PRIVADOS, MIEMBROS DE LOS PODERES DEL ESTADO',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (102,'ALTOS FUNCIONARIOS DE GOBIERNO',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (103,'FUNCIONARIOS DE GOBIERNOS MUNICIPALES, N.C.P.',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (104,'ALTOS FUNCIONARIOS DEL ÓRGANO JUDICIAL',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (105,'MAGISTRADO DE LA CORTE SUPREMA DE JUSTICIA',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (106,'ALTOS FUNCIONARIOS DEL ÓRGANO JUDICIAL, N.C.P.',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (107,'DIRECTIVOS DE RELACIONES EXTERIORES',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (108,'EMBAJADOR',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (109,'CÓNSUL',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (110,'DIRECTORES ADMINISTRATIVOS Y COMERCIALES',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (111,'DIRECTORES FINANCIEROS',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (112,'CONTADOR GENERAL DE EMPRESA',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (113,'AUDITOR GENERAL',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (114,'INGENIERO EN SISTEMAS INFORMÁTICOS',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (115,'PROFESIONALES EN DERECHO',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (116,'ABOGADOS',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (117,'NOTARIO',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (118,'ECONOMISTAS',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (119,'ACTORES',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (120,'PROFESIONALES DE NIVEL MEDIO DE SERVICIOS JURÍDICOS, SOCIALES, CULTURALES Y AFINES',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (121,'ASISTENTE DE BUFETE DE ABOGADOS',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (122,'PASANTE DE ABOGADOS',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (123,'AUXILIAR JURÍDICO',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (124,'ATLETAS Y DEPORTISTAS',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (125,'PRESTAMISTAS',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (126,'AGENTE DE VIAJES',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (127,'AGENTE DE POLICÍA NACIONAL CIVIL',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (128,'CONDUCTORES DE VEHÍCULOS Y OPERADORES DE EQUIPOS PESADOS MÓVILES',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (129,'CONDUCTORES DE CAMIONES PESADOS Y AUTOBUSES',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (130,'EXPERTOS EN CONTABILIDAD Y AUDITORÍA CONTABLE',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (131,'POLITÓLOGO',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (132,'PROFESIONALES RELIGIOSOS',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (133,'MÚSICOS, CANTANTES Y COMPOSITORES',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (134,'PILOTOS DE AVIACIÓN Y AFINES',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (135,'PROFESIONALES DE NIVEL MEDIO EN OPERACIONES FINANCIERAS Y ADMINISTRATIVAS',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (136,'AGENTES DE BOLSA, AGENTES DE CAMBIO Y OTROS SERVICIOS FINANCIEROS',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (137,'CAJEROS DE BANCOS Y AFINES',3,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (138,'PROFESIONALES, CIENTÍFICOS E INTELECTUALES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (139,'PROFESIONALES DE LAS CIENCIAS Y DE LA INGENIERÍA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (140,'FÍSICOS, QUÍMICOS Y AFINES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (141,'MERCADÓLOGO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (142,'ASTRÓNOMOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (143,'METEORÓLOGOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (144,'QUÍMICOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (145,'GEÓLOGOS Y GEOFÍSICOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (146,'MATEMÁTICOS, ACTUARIOS Y ESTADÍSTICOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (147,'BIÓLOGO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (148,'FARMACÓLOGO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (149,'ECOLOGISTA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (150,'INGENIEROS INDUSTRIALES Y DE PRODUCCIÓN',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (151,'INGENIEROS CIVILES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (152,'INGENIEROS MECÁNICOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (153,'INGENIEROS QUÍMICOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (154,'INGENIEROS ELECTRICISTAS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (155,'ARQUITECTOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (156,'DISEŃADOR DE MODAS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (157,'CARTÓGRAFOS Y TOPÓGRAFOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (158,'PROFESIONALES DE LA SALUD',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (159,'MÉDICOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (160,'MÉDICOS ESPECIALISTAS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (161,'PROFESIONALES DE ENFERMERÍA Y PARTERÍA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (162,'PROFESIONALES DE LA MEDICINA NATURAL Y ALTERNATIVA, N.C.P.',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (163,'VETERINARIOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (164,'ODONTÓLOGOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (165,'FARMACÉUTICOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (166,'FISIOTERAPEUTAS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (167,'NUTRICIONISTAS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (168,'OPTOMETRISTAS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (169,'PROFESORES DE UNIVERSIDADES Y DE LA ENSEŃANZA SUPERIOR',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (170,'PROFESORES DE TERCER CICLO Y BACHILLERATO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (171,'MAESTRO DE ENSEŃANZA PRIMARIA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (172,'OTROS PROFESORES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (173,'SOCIÓLOGOS Y ANTROPÓLOGOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (174,'ARQUEÓLOGO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (175,'FILÓSOFOS E HISTORIADORES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (176,'PSICÓLOGOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (177,'TRABAJADOR SOCIAL',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (178,'TEÓLOGO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (179,'AUTORES Y OTROS ESCRITORES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (180,'PERIODISTAS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (181,'YOUTUBER',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (182,'INFLUENCER',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (183,'TRADUCTORES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (184,'ESCULTORES, PINTORES ARTÍSTICOS Y AFINES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (185,'BAILARINES Y COREÓGRAFOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (186,'LOCUTORES DE RADIO, TELEVISIÓN Y OTROS MEDIOS DE COMUNICACIÓN',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (187,'ARTISTAS CREATIVOS E INTERPRETATIVOS NO CLASIFICADOS BAJO OTROS EPÍGRAFES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (188,'TÉCNICOS Y PROFESIONALES DE NIVEL MEDIO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (189,'TÉCNICOS EN CIENCIAS FÍSICAS Y EN INGENIERÍA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (190,'ANALISTA DE LABORATORIO QUÍMICO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (191,'ELECTROTÉCNICOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (192,'TÉCNICOS EN ELECTRÓNICA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (193,'TÉCNICO MECÁNICO DE REFRIGERACIÓN',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (194,'TÉCNICO MECÁNICO DE MOTORES DE VEHÍCULOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (195,'TÉCNICO MECÁNICO DE AIRE ACONDICIONADO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (196,'TÉCNICO DE INGENIERÍA AUTOMOTRIZ',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (197,'TÉCNICOS EN QUÍMICA INDUSTRIAL',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (198,'TÉCNICOS EN QUÍMICA INDUSTRIAL',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (199,'TÉCNICO EN INGENIERÍA DE MINAS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (200,'MAESTRO DE OBRA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (201,'TÉCNICOS EN CONTROL DE PROCESOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (202,'ASESOR DE CRÉDITO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (203,'ANALISTA DE CRÉDITO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (204,'GESTOR DE COBROS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (205,'ASISTENTE CONTABLE',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (206,'ASISTENTE DE AUDITORÍA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (207,'ASISTENTE DE COSTOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (208,'ASISTENTE DE PRESUPUESTO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (209,'TÉCNICOS EN CONTABILIDAD Y SIMILARES, N.C.P.',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (210,'AGENTES COMERCIALES Y CORREDORES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (211,'INSPECTOR DE POLICÍA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (212,'TÉCNICOS EN GALERÍAS DE ARTE, MUSEOS Y BIBLIOTECAS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (213,'COCINEROS PROFESIONALES (CHEFS) Y ASISTENTES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (214,'ARTISTA DE TATUAJES O TATUADOR',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (215,'OTROS PROFESIONALES DE NIVEL MEDIO EN ACTIVIDADES ARTÍSTICAS, N.C.P.',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (216,'TÉCNICO DE INGENIERÍA EN COMPUTACIÓN',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (217,'TÉCNICOS EN ASISTENCIA Y SOPORTE AL USUARIO DE TECNOLOGÍA DE LA INFORMACIÓN Y LAS COMUNICACIONES, N.C.P.',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (218,'OPERADOR DE EQUIPO MÓVIL DE TELEVISIÓN',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (219,'OPERADOR DE EQUIPO DE RADIODIFUSIÓN MÓVIL',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (220,'PERSONAL DE APOYO ADMINISTRATIVO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (221,'EMPLEADOS ADMINISTRATIVOS, N.C.P.',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (222,'CUIDADOR DE ANIMALES EN RESERVAS NATURAL O PARQUE ZOOLÓGICO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (223,'TRABAJADORES DE SERVICIOS PERSONALES, NO CLASIFICADOS BAJO OTROS EPÍGRAFES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (224,'VENDEDORES CALLEJEROS Y DE PUESTOS DE MERCADO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (225,'VENDEDOR AMBULANTE DE COMIDA PREPARADA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (226,'COMERCIANTES DE TIENDAS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (227,'COMERCIANTES DE PEQUEŃOS NEGOCIOS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (228,'VENDEDOR DE COMERCIO AL POR MENOR (FERRETERÍAS, TIENDAS, AGROSERVICIOS, FARMACIAS, VENTAS DE REPUESTOS, ABARROTERÍAS, ENTRE OTROS)',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (229,'MODELOS DE MODA, ARTE Y PUBLICIDAD',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (230,'VENDEDORES PUERTA A PUERTA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (231,'VENDEDORES POR TELÉFONO Y MEDIOS ELECTRÓNICOS, N.C.P.',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (232,'EXPENDEDORES DE GASOLINERAS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (233,'VENDEDORES, N.C.P.',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (234,'TRABAJADORES DE LOS CUIDADOS PERSONALES EN SERVICIOS DE SALUD',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (235,'BOMBEROS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (236,'ESCOLTA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (237,'AGENTE DE SEGURIDAD PRIVADA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (238,'VIGILANTE',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (239,'AGRICULTORES Y TRABAJADORES CALIFICADOS AGROPECUARIOS, FORESTALES Y PESQUEROS',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (240,'GANADERO',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (241,'AVICULTORES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (242,'APICULTORES Y SERICULTORES',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (243,'ACUICULTOR',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (244,'TAXISTA',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (245,'OPERADORES DE MAQUINARIA AGRÍCOLA Y FORESTAL MÓVIL',2,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (246,'PELUQUEROS, ESPECIALISTAS EN TRATAMIENTOS DE BELLEZA Y AFINES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (247,'CONSERJES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (248,'EMPLEADOS DE SERVICIOS FÚNEBRES Y EMBALSAMADORES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (249,'OFICIALES, OPERARIOS Y ARTESANOS DE ARTES MECÁNICAS Y DE OTROS OFICIOS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (250,'ALBAŃILES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (251,'CARPINTEROS DE ARMADO Y ACABADOS EN EDIFICIOS Y CASAS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (252,'OBREROS Y OPERARIOS DE LA CONSTRUCCIÓN (OBRA GRUESA) Y AFINES NO CLASIFICADOS PREVIAMENTE',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (253,'OFICIALES Y OPERARIOS DE LA CONSTRUCCIÓN (TRABAJOS DE ACABADO) Y AFINES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (254,'FONTANEROS E INSTALADORES DE TUBERÍAS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (255,'MECÁNICOS MONTADORES DE INSTALACIONES DE REFRIGERACIÓN Y CLIMATIZACIÓN',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (256,'PINTORES, LIMPIADORES DE FACHADAS Y AFINES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (257,'OPERARIOS DE ACABADO DE ARTÍCULOS Y ESTRUCTURAS DIVERSAS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (258,'MOLDEADORES, SOLDADORES, CHAPISTAS, CALDEREROS, MONTADORES DE ESTRUCTURAS METÁLICAS Y AFINES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (259,'TRABAJADORES DE LA FABRICACIÓN Y REPARACIÓN DE HERRAMIENTAS Y AFINES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (260,'OPERADORES DE MÁQUINAS HERRAMIENTAS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (261,'MECÁNICO INDUSTRIAL',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (262,'ARTESANOS Y OPERARIOS DE LAS ARTES GRÁFICAS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (263,'JOYEROS, ORFEBRES Y PLATEROS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (264,'ALFAREROS DEL BARRO, ARCILLA, ABRASIVOS Y SIMILARES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (265,'TRABAJADORES ESPECIALIZADOS EN ELECTRICIDAD Y LA ELECTROTECNOLOGÍA',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (266,'TÉCNICO EN HARDWARE (REPARADOR DE COMPUTADORAS)',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (267,'REPARADOR DE CELULARES Y TABLET',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (268,'INSTALADORES Y REPARADORES EN TECNOLOGÍA DE LA INFORMACIÓN, N.C.P.',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (269,'OPERARIOS Y OFICIALES DE PROCESAMIENTO DE ALIMENTOS, DE LA CONFECCIÓN, EBANISTAS, OTROS ARTESANOS Y AFINES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (270,'PANADEROS, PASTELEROS Y CONFITEROS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (271,'OTROS OPERARIOS DE LA CONSERVACIÓN DE FRUTAS, LEGUMBRES, VERDURAS Y AFINES, N.C.P.',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (272,'CATADORES Y CLASIFICADORES DE ALIMENTOS Y BEBIDAS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (273,'TRABAJADORES DEL TRATAMIENTO DE PIELES Y CUEROS, N.C.P.',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (274,'OPERARIOS DE INSTALACIONES Y MÁQUINAS Y ENSAMBLADORES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (275,'OPERADORES DE INSTALACIONES FIJAS Y MÁQUINAS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (276,'MINEROS Y OPERADORES DE INSTALACIONES MINERAS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (277,'TINTORERO DE LAVANDERÍA',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (278,'OPERADOR DE MÁQUINA',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (279,'ENSAMBLADORES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (280,'OCUPACIONES ELEMENTALES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (281,'LIMPIADORES Y ASISTENTES DOMÉSTICOS DE HOTELES Y OFICINAS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (282,'PERSONAL DE LIMPIEZA Y ASISTENTES DE OFICINAS, HOTELES Y OTROS ESTABLECIMIENTOS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (283,'JEFE DE SERVICIOS GENERALES (LIMPIEZA) EN EDIFICIOS',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (284,'PERSONAL DE LIMPIEZA, NO CLASIFICADO PREVIAMENTE',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (285,'AYUDANTE DE JARDINERÍA Y HORTICULTURA',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (286,'AYUDANTE DE LA INDUSTRIA DE PRODUCTOS DIVERSOS (TEXTILES, MADERA, METAL, ENTRE OTROS)',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (287,'VENDEDOR AMBULANTE DE PRODUCTOS NO COMESTIBLES (ARTESANÍAS, ARTÍCULOS METÁLICOS PEQUEŃOS, FLORES, TEXTILES, MEDICINA, ENTRE OTROS)',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (288,'MENSAJEROS, MANDADEROS, MALETEROS Y REPARTIDORES, N.C.P.',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (289,'OCUPACIONES MILITARES',1,1,1,current_timestamp());
INSERT INTO catalogoocgo (codigoCGO,descripcionCGO,riesgoCGO,idEstado,usuario_creacion,fecha_creacion) VALUES (290,'MIEMBROS DE LA TROPA DE LAS FUERZAS ARMADAS, N.C.P.',1,1,1,current_timestamp());
